import Head from "next/head";
import { createContext, useState } from "react";
import "../styles/globals.css";

export const cartContext = createContext();

function MyApp({ Component, pageProps }) {
  const [cart, setCart] = useState([]);
  return (
    <>
      <Head>
        <title>Next Book Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous"
        />
      </Head>
      <cartContext.Provider value={[cart, setCart]}>
        <Component {...pageProps} />
      </cartContext.Provider>
    </>
  );
}

export default MyApp;
